In [21]:
import pinocchio as pin
import numpy as np

In [22]:
model = pin.buildModelFromUrdf("urdf/h1.urdf", pin.JointModelFreeFlyer())
data = model.createData()

In [23]:
model.names[0]  # 'world'

'universe'

In [1]:
import networkx as nx
import matplotlib.pyplot as plt

G = nx.DiGraph()

for joint_id, joint in enumerate(model.joints[1:]):  # Skip universe
    parent = model.parents[joint.id]
    parent_name = model.names[parent]
    G.add_edge(parent_name, model.names[joint_id+1])

plt.figure(figsize=(18, 18))
nx.draw(G, with_labels=True, node_size=10, node_color='lightblue')
plt.title("Kinematic Tree of the Robot")
plt.show()

NameError: name 'model' is not defined

In [25]:
q = np.random.rand(model.nq)
print(q.shape)
vq = np.random.rand(model.nv)
print(vq.shape)

(26,)
(25,)


In [26]:
# M(q)
M = pin.crba(model, data, q)
print(M.shape)
h = pin.rnea(model, data, q, vq, np.zeros(25))
print(h.shape)

(25, 25)
(25,)


In [27]:
pin.centerOfMass(model, data, q, vq)

print(data.com[0]) # 
print(data.vcom[0])

[0.38635464 0.54200303 0.91891839]
[-0.11089729 -0.02586051  0.81195989]


In [32]:
for frame in model.frames:
    name = frame.name
    print(f"\n\n{name}, {model.getJointId(name)}")
    # print(data.com[model.getJointId(name)])




universe, 0


root_joint, 1


pelvis, 21


left_hip_yaw_joint, 2


left_hip_yaw_link, 21


left_hip_roll_joint, 3


left_hip_roll_link, 21


left_hip_pitch_joint, 4


left_hip_pitch_link, 21


left_knee_joint, 5


left_knee_link, 21


left_ankle_joint, 6


left_ankle_link, 21


right_hip_yaw_joint, 7


right_hip_yaw_link, 21


right_hip_roll_joint, 8


right_hip_roll_link, 21


right_hip_pitch_joint, 9


right_hip_pitch_link, 21


right_knee_joint, 10


right_knee_link, 21


right_ankle_joint, 11


right_ankle_link, 21


torso_joint, 12


torso_link, 21


d435_left_imager_joint, 21


d435_left_imager_link, 21


d435_rgb_module_joint, 21


d435_rgb_module_link, 21


imu_joint, 21


imu_link, 21


left_shoulder_pitch_joint, 13


left_shoulder_pitch_link, 21


left_shoulder_roll_joint, 14


left_shoulder_roll_link, 21


left_shoulder_yaw_joint, 15


left_shoulder_yaw_link, 21


left_elbow_joint, 16


left_elbow_link, 21


left_wrist_joint, 21


left_wrist_link, 21


logo_joint, 21


log

In [29]:
pin.getFrameJacobian(model, data, model.getFrameId("root_joint"), pin.ReferenceFrame.LOCAL).T.shape

(25, 6)

In [9]:
from pinocchio.visualize import MeshcatVisualizer

In [12]:
# geom_model = pin.buildGeomFromUrdf(model=model, urdf_filename="urdf/h1.urdf", package_dirs=["../.", "meshes"], geom_type=pin.GeometryType.VISUAL, geometry_model=None, mesh_loader=None)
geom_data = pin.GeometryData(collision_model)
geom_model = collision_model


In [13]:
viz = MeshcatVisualizer(model, geom_model, geom_model)
viz.initViewer()
viz.loadViewerModel()

# Display neutral pose
q = pin.neutral(model)
viz.display(q)


You can open the visualizer by visiting the following URL:
http://127.0.0.1:7000/static/


In [10]:
model, collision_model, visual_model = pin.buildModelsFromUrdf("urdf/h1.urdf", "../.")

In [19]:
import pinocchio as pin
import numpy as np

# Assumes you already have:
#   model, collision_model, visual_model = pin.buildModelsFromUrdf(urdf_path)
#   data  = pin.Data(model)
#   geom_data = pin.GeometryData(collision_model)

q = pin.neutral(model)
pin.forwardKinematics(model, data, q)
pin.updateFramePlacements(model, data)
pin.updateGeometryPlacements(model, data, collision_model, geom_data, q)

ankle_jid = model.getJointId("right_ankle_joint")   # <-- your joint name
parent_id = ankle_jid

pts = []

# Enumerate to get geometry ids; go has no .id
for gid, go in enumerate(collision_model.geometryObjects):
    # Keep only geometry attached to this joint (or, in some models, to its frame)
    if go.parentJoint != parent_id and getattr(go, "parentFrame", None) != parent_id:
        continue

    # world->geom and world->ankle
    oMg = geom_data.oMg[gid]          # SE3
    oMa = data.oMi[parent_id]         # SE3 (joint placement)
    aMg = oMa.inverse() * oMg         # ankle->geom

    # Try to access mesh vertices (depends on your HPP-FCL build)
    geom = go.geometry
    verts = None
    # Common cases: BVHModel* expose .vertices (numpy-like) and maybe .tri_indices/.triangles
    if hasattr(geom, "vertices"):
        # geom.vertices is typically a list/array of 3D points
        V = np.asarray(geom.vertices, dtype=float)          # (N,3)
        # Transform each vertex to the ankle frame
        Va = np.vstack([aMg.act(v) for v in V])             # (N,3)
        pts.append(Va)
    else:
        # Fallback: sample the geometry's local AABB corners if available,
        # or at least record its ankle-frame origin.
        try:
            # Some builds expose an AABB; if not, skip.
            aabb = geom.computeLocalAABB()                  # may not exist
            # Build 8 corners in geom frame, then map to ankle
            lo = np.array([aabb.min_[0], aabb.min_[1], aabb.min_[2]])
            hi = np.array([aabb.max_[0], aabb.max_[1], aabb.max_[2]])
            corners = np.array([[x,y,z] for x in [lo[0],hi[0]]
                                        for y in [lo[1],hi[1]]
                                        for z in [lo[2],hi[2]]])
            Va = np.vstack([aMg.act(v) for v in corners])
            pts.append(Va)
        except Exception:
            # As a last resort, take the geom origin in ankle frame
            pts.append(aMg.translation.reshape(1,3))

if not pts:
    raise RuntimeError("No collision geometry found under the specified ankle joint/frame.")

P = np.vstack(pts)                                   # (M,3) points in ANKLE frame

# --- Estimate sole plane/center from the lowest points in ankle-Z ---
z = P[:,2]
z_min = np.percentile(z, 1)                          # robust min
mask = np.abs(z - z_min) < 1e-3
ring = P[mask]
cx, cy = ring[:,0].mean(), ring[:,1].mean()
cz = z_min

# Orientation: set sole +Z = ankle +Z (often fine); tweak later if needed.
R_a_s = np.eye(3)
t_a_s = np.array([cx, cy, cz])
T_ankle_to_sole = pin.SE3(R_a_s, t_a_s)

print("T_ankle_to_sole:\n", T_ankle_to_sole)


T_ankle_to_sole:
   R =
1 0 0
0 1 0
0 0 1
  p =  0.05     0 -0.05



In [ ]:
import casadi
import numpy as np

opti = casadi.Opti()
x = opti.variable()
y = opti.variable()

opti.subject_to(x**2 + y >= 3)
opti.minimize(x**2 + y**2)

opti.solver('ipopt')
sol = opti.solve()
print(f"the soltution is x={sol.value(x)}, y={sol.value(y)}")

This is Ipopt version 3.11.9, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        2
Number of nonzeros in Lagrangian Hessian.............:        2

Error evaluating Jacobian of inequality constraints at user provided starting point.
  No scaling factors for inequality constraints computed!

Number of Iterations....: 0

Number of objective function evaluations             = 0
Number of objective gradient evaluations             = 0
Number of equality constraint evaluations            = 0
Number of inequality constraint evaluations          = 1
Number of equality constraint Jacobian evaluations   = 0
Number of inequality constraint Jacobian evaluations = 1
Number of Lagrangian Hessian evaluations             = 0
Total CPU secs in IPOPT (w/o function evaluations)   =      0.000
Total CPU secs in NLP func

CasADi - 2025-08-31 05:10:08 WARNING("solver:nlp_jac_g failed: Inf detected for output jac_g_x, at (row 0, col 1).") [.../casadi/core/oracle_function.cpp:393]
CasADi - 2025-08-31 05:10:08 WARNING("solver:nlp_jac_g failed: Inf detected for output jac_g_x, at (row 0, col 1).") [.../casadi/core/oracle_function.cpp:393]


RuntimeError: Error in Opti::solve [OptiNode] at .../casadi/core/optistack.cpp:165:
.../casadi/core/optistack_internal.cpp:1030: Assertion "return_success(accept_limit)" failed:
Solver failed. You may use opti.debug.value to investigate the latest values of variables. return_status is 'Invalid_Number_Detected'